from src.story_engine.scenarios.config import (
    ScenarioConfig,
    CharacterConfig,
    StoryletConfig,
    StoryBeatConfig,
    StateCondition,
    DramaConfig,
    ConflictConfig,
    ConflictTemplateConfig,
    PlotEntityConfig,
    PlotStageConfig,
    PlotRuleConfig,
    NeedConfig,
    ObligationConfig,
    RelationshipConfig,
    RelationshipDirectionConfig,
    RelationshipBitConfig,
    TraitConfig,
    NarrationConfig,
)


false_heiress_scenario = ScenarioConfig(
    name="真假千金",
    description="你是刚被沈家认回的亲生女儿林见微。回到这栋华丽又陌生的房子后，你很快发现：假千金并不打算让位，而父母、哥哥与她的未婚夫，似乎都本能地站在她那一边。",
    default_agent_runtime="hermes",
    physics_profile="mundane",
    environment="""
    [海城 · 沈宅]
    初秋傍晚，沈家老宅灯火通明。客厅、餐厅、二楼走廊和书房都收拾得一尘不染，佣人们压低了脚步，像是生怕碰碎这户人家表面的体面。
    这是一个现代都市家庭伦理爽文场景。冲突仍然发生在体面场合里，但允许茶言茶语、抢解释权、公开比较、装委屈、借规矩压人和漂亮话里的软刀子。
    玩家默认采用受限第一人称视角。除非异地事件明确传导到玩家面前，否则不要切出玩家所在场景。
    """,
    narration=NarrationConfig(
        guidance=[
            "整体节奏偏快，优先写清公开的不公平、站队、催促或小陷害。",
            "语言可以有锋利感，但角色不要自曝心机，普通动作也不要被写得诡异夸张。",
            "家庭冲突主要通过礼貌、座次、资源分配和漂亮话里的软刀子呈现。",
            "若结算中已经形成针对、偏心或误读，应落到听得见、看得见的具体刺点，不要只写成气氛压抑。",
        ],
        max_sentences=6,
        max_characters=220,
    ),
    initial_state="认亲后的第一顿正式家宴前，你一个人被佣人从客房请到客厅。你没有带任何人，也没有做出格的事，只是按吩咐过来。沈先生刚放下电话，沈夫人坐在沙发上，神色疏淡；哥哥沈砚川站在酒柜边，像是随时准备替谁收拾残局。沈昭宁已经先一步坐在母亲身侧，像在自己熟悉的位置上等你。陆承泽也在，他和沈昭宁订婚多年，此刻正替她拿着一杯温水，像是下意识站在她那边。没有人失礼，可这间屋子里每一道目光都在提醒你：你虽然是亲生的，却是刚回来的人。",
    initial_scene_flags={
        "day_phase": "arrival",
        "phase_turn": 0,
        "phase_schedule": [
            {"phase": "arrival", "label": "初到客厅", "start_step": 0},
            {"phase": "pre_dinner", "label": "家宴将开", "start_step": 1},
            {"phase": "dinner", "label": "正式家宴", "start_step": 2},
            {"phase": "after_dinner", "label": "饭后余波", "start_step": 4},
            {"phase": "night", "label": "夜里", "start_step": 6},
        ],
        "upcoming_commitments": [
            {
                "commitment_id": "dinner_summons",
                "title": "佣人开始请人入席",
                "summary": "饭前的寒暄正在收束，家里默认今晚的正式家宴马上要开始了。",
                "phase": "pre_dinner",
                "due_step": 1,
                "grace_steps": 0,
                "location": "沈宅客厅",
                "player_relevant": False,
                "present_consequence": "客厅里的停顿突然收紧，像是谁不打算再给你慢慢适应的余地。",
                "absent_consequence": "楼下已经在催人入席，节奏明显比你预想得更急。",
            },
            {
                "commitment_id": "family_dinner",
                "title": "认亲后的第一顿家宴",
                "summary": "这顿饭是沈家第一次把你放进明面上的位置里审视。",
                "phase": "dinner",
                "due_step": 2,
                "grace_steps": 0,
                "location": "餐厅",
                "player_relevant": True,
                "participants": [
                    "沈昭宁",
                    "沈先生",
                    "沈夫人",
                    "沈砚川",
                    "陆承泽",
                    "周姨",
                ],
                "wake_before_steps": 2,
                "present_consequence": "餐厅里的座次和照顾顺序会立刻把谁是自己人、谁是外来者摆到台面上。",
                "absent_consequence": "餐厅那边已经正式开席；你没过去，这件事几乎注定会被说成拿乔、不懂规矩或故意给人难堪。",
            },
            {
                "commitment_id": "after_dinner_settling",
                "title": "饭后的收束与传话",
                "summary": "饭局散后，佣人们开始收拾杯盘，真正的态度也更容易在走廊和转角里泄出来。",
                "phase": "after_dinner",
                "due_step": 4,
                "grace_steps": 0,
                "location": "二楼走廊",
                "player_relevant": False,
                "present_consequence": "饭一散，刚才桌上的话就开始在走廊里变形，像有人等着补上第二刀。",
                "absent_consequence": "饭后该散的已经散了，但显然有人不打算让今晚轻轻揭过。",
            },
            {
                "commitment_id": "study_light",
                "title": "书房深夜未熄的灯",
                "summary": "夜深以后，书房的灯仍亮着，像是有人在故意把某件旧事拖到更晚的时候。",
                "phase": "night",
                "due_step": 6,
                "grace_steps": 0,
                "location": "二楼走廊",
                "player_relevant": False,
                "present_consequence": "夜里的走廊安静得能听见书房门后的细碎动静，那盏灯迟迟没有熄。",
                "absent_consequence": "夜深了，书房那边仍有人没有睡，这件事明早不会毫无痕迹。",
            },
        ],
    },
    initial_world_objects={
        "沈宅客厅": {
            "kind": "living_room",
            "tags": ["family", "bias", "public", "arrival", "pre_dinner"],
            "aliases": ["客厅", "沙发边", "客厅里", "客厅那边"],
            "lighting": "warm",
            "atmosphere": "strained_polite",
            "connected_to": ["餐厅", "门厅", "二楼走廊"],
            "default_zone": "entry",
            "zones": {
                "entry": {"label": "靠门的入口处"},
                "main_sofa": {"label": "长沙发一侧"},
                "madam_side": {"label": "主沙发右手边"},
                "side_chair": {"label": "单人沙发旁"},
                "sideboard": {"label": "酒柜旁"},
                "window": {"label": "落地窗边"},
            },
        },
        "餐厅": {
            "kind": "dining_room",
            "tags": ["family", "bias", "public", "dinner"],
            "aliases": ["餐桌", "饭桌", "长桌", "桌边", "席上", "入席", "餐桌前"],
            "table_state": "set",
            "connected_to": ["沈宅客厅", "厨房走道"],
            "default_zone": "door",
            "zones": {
                "door": {"label": "餐厅门边"},
                "host_seat": {"label": "主位附近"},
                "left_side": {"label": "餐桌左侧"},
                "right_side": {"label": "餐桌右侧"},
                "service_path": {"label": "上菜通道边"},
            },
        },
        "二楼走廊": {
            "kind": "upstairs_hall",
            "tags": ["family", "aftermath", "night", "truth"],
            "aliases": ["楼上", "楼梯口", "走廊里"],
            "quiet": True,
            "connected_to": ["沈宅客厅", "书房", "客房"],
            "default_zone": "stairs",
            "zones": {
                "stairs": {"label": "楼梯口"},
                "study_door": {"label": "书房门边"},
                "guest_door": {"label": "客房门边"},
            },
        },
        "书房": {
            "kind": "study",
            "tags": ["study", "night", "truth"],
            "aliases": ["书桌前", "书架边", "书房里"],
            "door": "closed",
            "connected_to": ["二楼走廊"],
            "default_zone": "door",
            "zones": {
                "door": {"label": "书房门口"},
                "desk": {"label": "书桌前"},
                "shelf": {"label": "书架旁"},
            },
        },
        "客房": {
            "kind": "guest_room",
            "tags": ["private", "night", "aftermath"],
            "aliases": ["房间里", "卧室", "客房里"],
            "occupied": True,
            "connected_to": ["二楼走廊"],
            "default_zone": "inside",
            "zones": {
                "inside": {"label": "客房里侧"},
                "door": {"label": "客房门边"},
                "window": {"label": "床边窗前"},
            },
        },
        "门厅": {
            "kind": "foyer",
            "tags": ["arrival", "threshold"],
            "connected_to": ["沈宅客厅"],
            "default_zone": "inside",
            "zones": {"inside": {"label": "门厅内侧"}},
        },
        "厨房走道": {
            "kind": "service_hall",
            "tags": ["service", "background"],
            "connected_to": ["餐厅"],
            "default_zone": "passage",
            "zones": {"passage": {"label": "厨房走道"}},
        },
        "旧账册": {
            "is_location": False,
            "kind": "document",
            "owner": "周姨",
            "location": None,
            "hidden": True,
            "portable": True,
            "tags": ["old_record", "birth_secret"],
        },
    },
    initial_actor_states={
        "林见微": {
            "location": "沈宅客厅",
            "sub_location": "entry",
            "stance": "standing",
            "focus_target": "沈昭宁",
            "public_status": "刚认回的真千金",
            "pressure": 3,
            "family_support": -2,
        },
        "沈昭宁": {
            "location": "沈宅客厅",
            "sub_location": "main_sofa",
            "stance": "seated",
            "focus_target": "林见微",
            "side_with": "沈夫人",
            "dramatic_motive": "保住自己在沈家的位置",
            "pressure_profile": "white_lotus",
            "public_lever": "委屈、误会和体贴式比较",
            "signature_templates": ["white_lotus_needling", "small_object_frame", "public_comparison_cut"],
            "dramatic_push": 5,
            "public_status": "养大的千金",
            "territorial": True,
            "framing_style": "white_lotus",
        },
        "沈先生": {
            "location": "沈宅客厅",
            "sub_location": "window",
            "stance": "standing",
            "focus_target": "林见微",
            "side_with": "沈昭宁",
            "dramatic_motive": "压住场面，不让家里失控丢脸",
            "pressure_profile": "order_control",
            "public_lever": "规矩、秩序和长辈权威",
            "signature_templates": ["family_public_blame"],
            "dramatic_push": 4,
            "attitude": "stern",
            "bias": "沈昭宁",
        },
        "沈夫人": {
            "location": "沈宅客厅",
            "sub_location": "madam_side",
            "stance": "seated",
            "focus_target": "林见微",
            "side_with": "沈昭宁",
            "dramatic_motive": "维持体面，同时继续偏护自己养大的女儿",
            "pressure_profile": "polite_comparison",
            "public_lever": "礼数、照顾顺序和分寸比较",
            "signature_templates": ["public_comparison_cut", "dining_seating_slight"],
            "dramatic_push": 4,
            "attitude": "measured",
            "bias": "沈昭宁",
        },
        "沈砚川": {
            "location": "沈宅客厅",
            "sub_location": "sideboard",
            "stance": "leaning",
            "focus_target": "林见微",
            "side_with": "沈昭宁",
            "dramatic_motive": "替沈昭宁截断麻烦，尽快给场面定调",
            "pressure_profile": "cutoff_guard",
            "public_lever": "打断、定调和逼人退一步",
            "signature_templates": ["brother_shuts_you_down", "family_public_blame"],
            "dramatic_push": 4,
            "attitude": "cool",
            "bias": "沈昭宁",
        },
        "陆承泽": {
            "location": "沈宅客厅",
            "sub_location": "side_chair",
            "stance": "standing",
            "focus_target": "沈昭宁",
            "side_with": "沈昭宁",
            "dramatic_motive": "用旧情和体面先替沈昭宁抢走解释权",
            "pressure_profile": "shielding",
            "public_lever": "旧情、熟悉感和貌似公平的解释",
            "signature_templates": ["engagement_side_with_her", "dining_seating_slight"],
            "dramatic_push": 3,
            "attitude": "reserved",
            "bias": "沈昭宁",
        },
        "周姨": {
            "location": "餐厅",
            "sub_location": "service_path",
            "stance": "standing",
            "dramatic_motive": "尽量维持运转，但会偷偷给林见微一点提醒",
            "pressure_profile": "quiet_hint",
            "public_lever": "传话、旧物和细碎提醒",
            "signature_templates": [],
            "dramatic_push": 1,
            "attitude": "careful",
            "loyalty": "household",
        },
    },
    initial_relationships=[
        RelationshipConfig(
            participants=["林见微", "周姨"],
            directions=[
                RelationshipDirectionConfig(source="林见微", target="周姨", tracks={"favor": 1}),
                RelationshipDirectionConfig(source="周姨", target="林见微", tracks={"favor": 2, "malice": 0}),
            ],
            bits=[RelationshipBitConfig(bit_id="household_staff")],
        ),
        RelationshipConfig(
            participants=["林见微", "沈昭宁"],
            directions=[
                RelationshipDirectionConfig(source="林见微", target="沈昭宁", tracks={"malice": 2}),
                RelationshipDirectionConfig(source="沈昭宁", target="林见微", tracks={"favor": 0, "malice": 4}),
            ],
            bits=[RelationshipBitConfig(bit_id="family_sisters")],
        ),
        RelationshipConfig(
            participants=["沈昭宁", "沈夫人"],
            directions=[
                RelationshipDirectionConfig(source="沈昭宁", target="沈夫人", tracks={"favor": 4}),
                RelationshipDirectionConfig(source="沈夫人", target="沈昭宁", tracks={"favor": 4}),
            ],
            bits=[RelationshipBitConfig(bit_id="family_parent_child")],
        ),
        RelationshipConfig(
            participants=["沈昭宁", "沈砚川"],
            directions=[
                RelationshipDirectionConfig(source="沈昭宁", target="沈砚川", tracks={"favor": 4}),
                RelationshipDirectionConfig(source="沈砚川", target="沈昭宁", tracks={"favor": 4}),
            ],
            bits=[RelationshipBitConfig(bit_id="family_siblings")],
        ),
        RelationshipConfig(
            participants=["沈昭宁", "陆承泽"],
            directions=[
                RelationshipDirectionConfig(source="沈昭宁", target="陆承泽", tracks={"favor": 5}),
                RelationshipDirectionConfig(source="陆承泽", target="沈昭宁", tracks={"favor": 5}),
            ],
            bits=[RelationshipBitConfig(bit_id="engaged")],
        ),
        RelationshipConfig(
            participants=["沈先生", "林见微"],
            directions=[RelationshipDirectionConfig(source="沈先生", target="林见微", tracks={"favor": 1, "malice": 1, "trust": -2})],
            bits=[RelationshipBitConfig(bit_id="family_parent_child")],
        ),
        RelationshipConfig(
            participants=["沈先生", "沈昭宁"],
            directions=[RelationshipDirectionConfig(source="沈先生", target="沈昭宁", tracks={"favor": 3})],
            bits=[RelationshipBitConfig(bit_id="family_parent_child")],
        ),
        RelationshipConfig(
            participants=["沈夫人", "林见微"],
            directions=[RelationshipDirectionConfig(source="沈夫人", target="林见微", tracks={"favor": 1, "malice": 1, "trust": -1})],
            bits=[RelationshipBitConfig(bit_id="family_parent_child")],
        ),
        RelationshipConfig(
            participants=["沈砚川", "林见微"],
            directions=[RelationshipDirectionConfig(source="沈砚川", target="林见微", tracks={"favor": 0, "malice": 2, "trust": -2})],
            bits=[RelationshipBitConfig(bit_id="family_siblings")],
        ),
        RelationshipConfig(
            participants=["陆承泽", "林见微"],
            directions=[RelationshipDirectionConfig(source="陆承泽", target="林见微", tracks={"favor": 0, "malice": 2, "trust": -2})],
        ),
    ],
    storylets=[
        StoryletConfig(
            storylet_id="arrival_cold_reception",
            intent="让家人一开场就通过称呼、招呼顺序或谁先被照顾，直接把玩家放在较尴尬的位置上。",
            priority=95,
            one_shot=False,
            tags=["family", "bias"],
            situation_kinds=["frontstage", "plot_pressure"],
            situation_tags=["family", "bias"],
            beat=StoryBeatConfig(
                beat_type="cold_reception",
                visibility="public",
                preferred_actors=["沈夫人", "沈昭宁"],
                preferred_template_ids=["public_comparison_cut"],
                required_flags=["comparison", "public"],
                target_actor="林见微",
                stake="belonging",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="in", value=["arrival", "pre_dinner"]),
                StateCondition(scope="actor", target="林见微", path="location", operator="eq", value="沈宅客厅"),
                StateCondition(scope="actor", target="沈昭宁", path="location", operator="eq", value="沈宅客厅"),
            ],
        ),
        StoryletConfig(
            storylet_id="white_lotus_opening_move",
            intent="让沈昭宁开场就先示好，再迅速把一句话、一个座位或一杯水扭成自己受了委屈，逼玩家立刻吃下第一口闷亏。",
            priority=97,
            one_shot=False,
            tags=["trap", "social", "white_lotus"],
            situation_kinds=["frontstage", "plot_pressure"],
            situation_tags=["trap", "white_lotus"],
            beat=StoryBeatConfig(
                beat_type="white_lotus",
                visibility="public",
                preferred_actors=["沈昭宁"],
                preferred_template_ids=["white_lotus_needling"],
                required_flags=["white_lotus", "trap"],
                target_actor="林见微",
                stake="reputation",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="in", value=["arrival", "pre_dinner"]),
                StateCondition(scope="actor", target="林见微", path="location", operator="eq", value="沈宅客厅"),
                StateCondition(scope="actor", target="沈昭宁", path="location", operator="eq", value="沈宅客厅"),
            ],
        ),
        StoryletConfig(
            storylet_id="dinner_seating_cut",
            intent="进入餐厅后，立刻用座次、上菜顺序、谁被顺手照顾这些小事做成公开站队，让玩家马上感到自己被放在次要位置。",
            priority=98,
            one_shot=False,
            tags=["dinner", "bias", "public"],
            situation_kinds=["frontstage", "commitment", "plot_pressure"],
            situation_tags=["dinner", "bias", "public"],
            beat=StoryBeatConfig(
                beat_type="seating_slight",
                visibility="public",
                preferred_actors=["沈夫人", "陆承泽"],
                preferred_template_ids=["dining_seating_slight", "engagement_side_with_her"],
                required_flags=["dinner", "bias", "public"],
                target_actor="林见微",
                stake="position",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="eq", value="dinner"),
                StateCondition(scope="actor", target="林见微", path="location", operator="eq", value="餐厅"),
                StateCondition(scope="actor", target="沈昭宁", path="location", operator="eq", value="餐厅"),
            ],
        ),
        StoryletConfig(
            storylet_id="family_closes_ranks",
            intent="只要沈昭宁稍露委屈，就让父母、哥哥或陆承泽立刻护上去，并把问题转成玩家不懂事、太敏感或不给面子。",
            priority=96,
            one_shot=False,
            tags=["bias", "pressure", "family"],
            situation_kinds=["frontstage", "plot_pressure"],
            situation_tags=["family", "bias", "pressure"],
            beat=StoryBeatConfig(
                beat_type="family_closes_ranks",
                visibility="public",
                preferred_actors=["沈先生", "沈夫人", "沈砚川", "陆承泽"],
                preferred_template_ids=["family_public_blame", "brother_shuts_you_down", "engagement_side_with_her"],
                required_flags=["family_bias", "public_blame"],
                target_actor="林见微",
                stake="standing",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="in", value=["dinner", "after_dinner"]),
                StateCondition(scope="plot", target="framing_game", path="clock", operator="gte", value=1),
            ],
        ),
        StoryletConfig(
            storylet_id="small_object_frame",
            intent="用茶杯、餐巾、座位上的东西或一道菜迅速做局，让玩家当众显得像做错了什么，方便别人顺势批她一嘴。",
            priority=94,
            one_shot=False,
            tags=["trap", "object", "public"],
            situation_kinds=["frontstage", "plot_pressure"],
            situation_tags=["trap", "public"],
            beat=StoryBeatConfig(
                beat_type="small_object_frame",
                visibility="public",
                preferred_actors=["沈昭宁"],
                preferred_template_ids=["small_object_frame"],
                required_flags=["object", "trap", "public"],
                target_actor="林见微",
                stake="face",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="eq", value="dinner"),
                StateCondition(scope="actor", target="林见微", path="location", operator="eq", value="餐厅"),
                StateCondition(scope="actor", target="沈昭宁", path="location", operator="eq", value="餐厅"),
            ],
        ),
        StoryletConfig(
            storylet_id="first_round_public_blame",
            intent="在晚宴刚开始或刚被催入席时，就安排一句不轻不重却足够扎人的话，让玩家当场承担“让大家等你”“不懂礼数”之类的名声压力。",
            priority=99,
            one_shot=False,
            tags=["public", "blame", "fast"],
            situation_kinds=["frontstage", "commitment"],
            situation_tags=["public", "pre_dinner", "dinner"],
            beat=StoryBeatConfig(
                beat_type="public_blame",
                visibility="public",
                preferred_actors=["沈先生", "沈夫人"],
                preferred_template_ids=["family_public_blame"],
                required_flags=["public_blame"],
                target_actor="林见微",
                stake="reputation",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="in", value=["pre_dinner", "dinner"]),
                StateCondition(scope="plot", target="household_bias", path="clock", operator="gte", value=1),
            ],
        ),
        StoryletConfig(
            storylet_id="missed_dinner_aftertaste",
            intent="如果玩家没赶上家宴，就让她立刻吃到余波：有人已经替她定性，甚至把她塑造成不识抬举的人。",
            priority=88,
            one_shot=False,
            tags=["absence", "reputation", "family"],
            situation_kinds=["transition", "aftermath"],
            situation_tags=["absence"],
            beat=StoryBeatConfig(
                beat_type="absence_aftertaste",
                visibility="public",
                preferred_actors=["沈夫人", "沈砚川"],
                preferred_template_ids=["family_public_blame"],
                required_flags=["absence", "public_blame"],
                target_actor="林见微",
                stake="reputation",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.last_missed_commitment.commitment_id", operator="eq", value="family_dinner"),
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="in", value=["after_dinner", "night"]),
            ],
        ),
        StoryletConfig(
            storylet_id="housekeeper_remembers",
            intent="让周姨在送茶、收拾旧物或压低声音提醒路线时，流露出一点更偏向玩家身世的迟疑线索。",
            priority=78,
            one_shot=True,
            tags=["clue", "servant"],
            situation_kinds=["plot_pressure", "frontstage"],
            situation_tags=["truth", "night", "study"],
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="in", value=["after_dinner", "night"]),
                StateCondition(scope="actor", target="林见微", path="location", operator="in", value=["二楼走廊", "客房", "书房"]),
                StateCondition(scope="plot", target="buried_birth_secret", path="clock", operator="gte", value=1),
            ],
        ),
        StoryletConfig(
            storylet_id="engagement_pressure_turns",
            intent="让陆承泽或家人借旧婚约和旧情分公开护着沈昭宁，使玩家在场时也插不上话，体面上直接落下风。",
            priority=90,
            one_shot=False,
            tags=["engagement", "bias", "public"],
            situation_kinds=["frontstage", "plot_pressure"],
            situation_tags=["engagement", "public"],
            beat=StoryBeatConfig(
                beat_type="engagement_pressure",
                visibility="public",
                preferred_actors=["陆承泽"],
                preferred_template_ids=["engagement_side_with_her"],
                required_flags=["engagement_pressure", "bias"],
                target_actor="林见微",
                stake="explanation_right",
            ),
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="in", value=["dinner", "after_dinner"]),
                StateCondition(scope="plot", target="engagement_leverage", path="clock", operator="gte", value=1),
            ],
        ),
        StoryletConfig(
            storylet_id="study_light_lures_truth",
            intent="到夜里时，让书房门缝里的灯、门外停顿的脚步、压低的说话声或某份文件的边角，把玩家往更深的旧事边缘引过去。",
            priority=80,
            one_shot=False,
            tags=["night", "truth", "study"],
            situation_kinds=["frontstage", "plot_pressure"],
            situation_tags=["night", "truth", "study"],
            conditions=[
                StateCondition(scope="scene", path="scene_flags.day_phase", operator="eq", value="night"),
                StateCondition(scope="actor", target="林见微", path="location", operator="in", value=["二楼走廊", "书房"]),
                StateCondition(scope="plot", target="buried_birth_secret", path="clock", operator="gte", value=1),
            ],
        ),
    ],
    drama=DramaConfig(
        initial_tension=0.64,
        target_min=0.83,
        target_max=0.96,
        crisis_threshold=0.72,
        recovery_bias=0.0,
    ),
    conflict=ConflictConfig(
        intensity=0.96,
        max_quiet_turns=1,
        early_pressure_window_end=2,
        antagonist_names=["沈昭宁", "沈先生", "沈夫人", "沈砚川", "陆承泽"],
        preferred_modes=["white_lotus", "provocation", "public_blame", "family_bias", "comparison", "engagement_pressure"],
        surface_style="acid",
        verbal_directness=0.98,
        repetition_window=3,
    ),
    conflict_templates=[
        ConflictTemplateConfig(
            template_id="white_lotus_needling",
            instruction="让沈昭宁带着体贴或委屈的口吻当众说一句像在替玩家圆场、实则把玩家放到失礼位置上的话；她可以显得温柔，但必须让玩家明显感到被轻轻踩了一脚。",
            fallback_results=[
                "先笑着替你说“刚回来不懂家里的规矩也正常”，像在解围，实际却先替你认下了失礼。",
                "温温柔柔地接过你的话，轻描淡写地补了一句“姐姐别急，大家不会怪你的”，把你说得像是先闹了脾气。",
                "主动把姿态放得很低，嘴上说怕你不自在，结果却让满桌人都听出来你才是那个打乱场面的外人。",
            ],
            phases=["arrival", "pre_dinner", "dinner"],
            preferred_actors=["沈昭宁"],
            tags=["white_lotus", "public", "trap", "provocation"],
            min_step=0,
        ),
        ConflictTemplateConfig(
            template_id="public_comparison_cut",
            instruction="让沈昭宁或家人当众做一次轻飘飘的比较，把沈昭宁衬得更懂事、更体面，从而让玩家吃亏。",
            fallback_results=[
                "轻飘飘地拿你和眼前那份“懂事体面”做了个比较，没带脏字，却把高下摆到了台面上。",
                "像是顺口感慨了一句“总有人更会顾全场面”，话不重，却刚好压在你开口之后。",
                "拿这些年的分寸感做了个对照，让你明明什么都没错，也像显得太扎眼。",
            ],
            phases=["arrival", "pre_dinner", "dinner", "after_dinner"],
            preferred_actors=["沈昭宁", "沈夫人", "沈砚川"],
            tags=["comparison", "public", "provocation"],
            min_step=0,
        ),
        ConflictTemplateConfig(
            template_id="family_public_blame",
            instruction="让一位家人立刻拿规矩、教养、场合或长幼秩序压玩家一句，让场面出现清晰的站队；要让玩家能感到那不是单纯提醒，而是压制。",
            fallback_results=[
                "当众拿规矩压了你一句，像是在维持场面，其实是在堵你的嘴。",
                "语气平平地提醒你别让长辈久等，可那句话落下来，等于把不懂事的帽子先扣到了你头上。",
                "不肯给你多解释半句的机会，先把“今天不是你闹脾气的时候”这种立场摆了出来。",
            ],
            phases=["pre_dinner", "dinner", "after_dinner"],
            preferred_actors=["沈先生", "沈夫人", "沈砚川"],
            tags=["public_blame", "family_bias", "provocation"],
            min_step=0,
        ),
        ConflictTemplateConfig(
            template_id="dining_seating_slight",
            instruction="让餐厅里的座次、照顾顺序或谁先被招呼这类体面细节，当场把玩家放到次要位置。",
            fallback_results=[
                "座位看着都留了出来，可真正顺手被照顾、被先招呼的人还是沈昭宁，你的位置像是临时补上的。",
                "餐桌边的顺序安排得滴水不漏，偏偏轮到你时只剩一句轻飘飘的“先坐那边吧”。",
                "谁该靠近主位、谁只适合坐在边上，这套无声的安排把亲疏摆得比任何一句话都更明白。",
            ],
            phases=["dinner"],
            preferred_actors=["沈夫人", "陆承泽"],
            tags=["dinner", "bias", "public", "comparison"],
            min_step=1,
        ),
        ConflictTemplateConfig(
            template_id="small_object_frame",
            instruction="让一个杯子、餐巾或小物件被借题发挥，迅速把玩家推到像是做错事的位置上。",
            fallback_results=[
                "沈昭宁先轻声说那只杯子是母亲惯用的，话说得很软，却足够让旁人把视线都落到你手边。",
                "不过是一张餐巾的位置歪了些，她先替你圆一句“姐姐不是故意的”，倒像默认你已经失了手。",
                "一道菜刚转到你面前，她就温温柔柔地提醒“这个口味妈妈吃不惯”，把你衬得像是只顾自己。",
            ],
            phases=["dinner", "after_dinner"],
            preferred_actors=["沈昭宁"],
            tags=["object", "trap", "public", "white_lotus"],
            min_step=1,
        ),
        ConflictTemplateConfig(
            template_id="brother_shuts_you_down",
            instruction="让沈砚川用哥哥式的冷静口吻打断玩家，像是在收场，实际上是替沈昭宁截断玩家的反击窗口。",
            fallback_results=[
                "平静地把你的话截断了，像是在主持秩序，实际却默认你才是麻烦的来源。",
                "看似公允地让你“先别把场面弄僵”，等于直接宣布你再说下去就是不识趣。",
                "话不重，却精准地把你钉回了“别在这里失态”的位置上。",
            ],
            phases=["dinner", "after_dinner"],
            preferred_actors=["沈砚川"],
            tags=["family_bias", "public_blame", "provocation"],
            min_step=1,
        ),
        ConflictTemplateConfig(
            template_id="engagement_side_with_her",
            instruction="让陆承泽在公开场合顺手站到沈昭宁那边，像是在维持体面，实际却把解释权从玩家手里拿走。",
            fallback_results=[
                "很自然地站到了沈昭宁那边，口气平静，却先把你的解释压了下去。",
                "替沈昭宁把椅子、台阶和体面都铺好了，轮到你时，只剩一句冷静的“先别说这个”。",
                "像是在讲道理，却默认你的情绪和立场都不值得先被听见。",
            ],
            phases=["dinner", "after_dinner"],
            preferred_actors=["陆承泽"],
            tags=["engagement_pressure", "public", "bias"],
            min_step=1,
        ),
    ],
    plot_entities=[
        PlotEntityConfig(
            plot_id="household_bias",
            title="整屋子的偏心",
            description="沈家上下嘴上讲体面，实际却在一次次站位中默认偏向沈昭宁。",
            clock=2,
            max_clock=4,
            current_stage=0,
            tags=["family", "bias"],
            stages=[
                PlotStageConfig(
                    label="默认",
                    summary="所有人都下意识把沈昭宁当自己人，把玩家当客人。",
                    pressure_hint="用座位、称呼、谁被先照顾来体现偏心。",
                ),
                PlotStageConfig(
                    label="护短",
                    summary="当冲突出现时，家人会先替沈昭宁解释。",
                    pressure_hint="让父母、哥哥或未婚夫优先质疑玩家的动机。",
                ),
                PlotStageConfig(
                    label="失衡",
                    summary="偏心开始不再只是态度，而会影响资源、信任和解释权。",
                    pressure_hint="让玩家切身感到自己即便占理，也不一定有人听。",
                ),
                PlotStageConfig(
                    label="反噬",
                    summary="这种偏心终于把某个更大的真相推向台前。",
                    pressure_hint="让一次看似维护体面的偏帮，暴露家里更深的裂缝。",
                ),
            ],
        ),
        PlotEntityConfig(
            plot_id="framing_game",
            title="白莲花设局",
            description="沈昭宁不会明着发难，她更习惯把示好、委屈和误会拧成对自己有利的局面。",
            clock=2,
            max_clock=4,
            current_stage=0,
            tags=["trap", "white_lotus"],
            stages=[
                PlotStageConfig(
                    label="铺垫",
                    summary="她先用温柔和懂事占住道德高地。",
                    pressure_hint="让她先示好，再借一个细节显得自己被误解或受委屈。",
                ),
                PlotStageConfig(
                    label="借势",
                    summary="她开始学会借父母、哥哥和未婚夫的偏心完成设局。",
                    pressure_hint="让别人的护短替她把局做完整，不必自己说重话。",
                ),
                PlotStageConfig(
                    label="反咬",
                    summary="玩家越解释，越容易在众人眼里显得咄咄逼人。",
                    pressure_hint="让玩家的合理反应也可能被转译成失态。",
                ),
                PlotStageConfig(
                    label="翻车",
                    summary="设局越来越密，终有一次会留下破绽。",
                    pressure_hint="保留一些可供玩家反制的细小漏洞，不要让陷害无懈可击。",
                ),
            ],
        ),
        PlotEntityConfig(
            plot_id="buried_birth_secret",
            title="被埋住的身世细节",
            description="关于当年抱错或调换的细节，并没有随着认亲尘埃落定。",
            clock=0,
            max_clock=3,
            current_stage=0,
            tags=["truth", "document"],
            stages=[
                PlotStageConfig(
                    label="噤声",
                    summary="家里默认认亲结果已定，不想再追问旧事。",
                    pressure_hint="让书房、旧文件、旧医院和年份成为不好碰的话题。",
                ),
                PlotStageConfig(
                    label="松动",
                    summary="一些细节开始互相对不上。",
                    pressure_hint="让周姨、旧物、照片或某句话露出缝隙。",
                ),
                PlotStageConfig(
                    label="逼近",
                    summary="真相逼近，但说出真相未必会让玩家得到公平。",
                    pressure_hint="让玩家意识到真相之外，仍有关系和立场的代价。",
                ),
            ],
        ),
        PlotEntityConfig(
            plot_id="engagement_leverage",
            title="被借走的旧婚约立场",
            description="陆承泽与沈昭宁多年旧情未断，这段关系不仅影响站队，也会被反过来当成压制玩家的社会工具。",
            clock=1,
            max_clock=4,
            current_stage=0,
            tags=["engagement", "status", "public"],
            stages=[
                PlotStageConfig(
                    label="余温",
                    summary="旧婚约虽然名义上尴尬，却还在无形地给沈昭宁撑场面。",
                    pressure_hint="让陆承泽的熟悉感和维护姿态本身成为一种偏心。",
                ),
                PlotStageConfig(
                    label="借口",
                    summary="家里开始把这段旧关系当成合理照顾沈昭宁的借口。",
                    pressure_hint="让别人以体谅、旧情和局面复杂为由，要求玩家退一步。",
                ),
                PlotStageConfig(
                    label="错位",
                    summary="旧婚约带来的站位越来越不像私事，而开始影响玩家的声誉和解释权。",
                    pressure_hint="让公开场合里谁替谁说话，变成一把能割人的软刀子。",
                ),
                PlotStageConfig(
                    label="松裂",
                    summary="这层默认的旧情关系终于出现裂缝，某个人开始意识到自己一直站错了边。",
                    pressure_hint="保留一个能让玩家撬动立场的破口，但不要来得太容易。",
                ),
            ],
        ),
    ],
    plot_rules=[
        PlotRuleConfig(
            rule_id="player_enters_family_dinner",
            plot_id="household_bias",
            conditions=[
                StateCondition(scope="actor", target="林见微", path="location", operator="eq", value="餐厅"),
            ],
            advance=1,
            one_shot=True,
            reason="林见微实际进入家宴场景，家庭偏心从背景关系进入公开站位。",
        ),
        PlotRuleConfig(
            rule_id="birth_secret_study_access",
            plot_id="buried_birth_secret",
            conditions=[
                StateCondition(scope="actor", target="林见微", path="location", operator="eq", value="书房"),
            ],
            advance=1,
            one_shot=True,
            reason="林见微实际进入书房，旧文件与出生秘密获得被发现的现实机会。",
        ),
    ],
    characters=[
        CharacterConfig(
            name="林见微",
            agent_runtime="hermes",
            role="沈家刚认回的亲生女儿",
            personality="敏感、克制、自尊心强，习惯先观察后开口。你不想乞求施舍般的亲情，但也不会轻易放弃属于自己的位置。",
            goals=[
                "在这顿家宴里站稳脚跟，不被当成局外人",
                "判断谁是真偏心、谁只是习惯性站队",
                "识破沈昭宁的手段，并尽量保住自己的体面",
            ],
            initial_beliefs=[
                {"statement": "沈家人更信任沈昭宁，而不是刚回来的自己", "confidence": 0.8, "source": "初到沈宅时的观察"},
            ],
            initial_commitments=["在确认事实前，不轻易把自己的底牌交出去"],
            initial_needs=[
                NeedConfig(name="尊严与归属", pressure=0.68, drift_per_turn=0.04, description="持续被当作外人会推动她争取位置或退出羞辱场面"),
            ],
            initial_traits=[
                TraitConfig(trait_id="observant", intensity=0.8),
                TraitConfig(trait_id="proud", intensity=0.75),
            ],
            risk_tolerance=0.5,
            initial_obligations=[
                ObligationConfig(
                    obligation_id="decide_family_dinner",
                    title="在正式开席前决定是否进入家宴",
                    summary="无论入席还是拒绝，都必须在家宴节奏把自己裹进去前作出选择",
                    creditor="沈先生",
                    due_step=2,
                    grace_steps=0,
                    wake_before_steps=1,
                    pressure_need="尊严与归属",
                    completion_conditions=[
                        StateCondition(
                            scope="actor",
                            target="林见微",
                            path="location",
                            operator="eq",
                            value="餐厅",
                        )
                    ],
                )
            ],
            is_player=True,
        ),
        CharacterConfig(
            name="沈昭宁",
            agent_runtime="hermes",
            role="沈家养大的千金（假的）",
            personality="聪明、漂亮、擅长示弱和把握分寸。她最怕失去位置，因此会把自己包装成最委屈、最懂事的那个人。",
            goals=[
                "保住自己在沈家的位置和情感中心",
                "让家人继续相信林见微才是麻烦的制造者",
                "在不显得恶毒的前提下给林见微制造难堪",
                "用示弱、让步、含泪解释、公开比较和借他人护短来完成设局",
            ],
            initial_beliefs=[
                {"statement": "只要自己显得足够懂事，家人就会继续保护自己", "confidence": 0.9, "source": "多年家庭经验"},
                {"statement": "林见微回来后会夺走自己的位置", "confidence": 0.75, "source": "恐惧与推测"},
            ],
            initial_secrets=["自己真正害怕的不是失去财富，而是被家人承认可以被替代"],
            initial_commitments=["绝不在众人面前直接承认自己有敌意"],
            initial_needs=[
                NeedConfig(name="位置安全", pressure=0.78, drift_per_turn=0.05, critical_threshold=0.85, description="林见微被接纳得越多，她越迫切地维护自己的家庭中心位置"),
            ],
            initial_traits=[
                TraitConfig(trait_id="calculating", intensity=0.9),
                TraitConfig(trait_id="status_anxious", intensity=0.8),
            ],
            risk_tolerance=0.66,
            is_player=False,
            llm_config={
                "system_instruction_extras": "你不会直接承认自己在陷害。你更擅长装作无辜、委屈、好心，顺势让别人误会对方。你可以茶言茶语、抢解释权、当众比较、看似体贴地刺人，但不要直接自曝恶意。"
            },
        ),
        CharacterConfig(
            name="沈先生",
            agent_runtime="hermes",
            role="父亲",
            personality="严厉、讲秩序、看重结果和脸面。即使知道林见微是亲生的，也不习惯立刻把感情给她。",
            goals=[
                "维持家里的秩序和体面",
                "尽量避免今晚闹出难堪场面",
                "在冲突里本能地偏向自己更熟悉的沈昭宁",
                "如果需要批评谁，优先用‘规矩’和‘大局’去压林见微",
            ],
            initial_beliefs=[
                {"statement": "熟悉家中规矩的人通常比情绪激动的人更可信", "confidence": 0.8, "source": "长期处事习惯"},
            ],
            initial_needs=[
                NeedConfig(name="秩序控制", pressure=0.65, drift_per_turn=0.03, description="公开争执和不服从会推动他迅速定调和压制场面"),
            ],
            initial_traits=[
                TraitConfig(trait_id="authoritarian", intensity=0.8),
                TraitConfig(trait_id="orderly", intensity=0.8),
            ],
            risk_tolerance=0.45,
            is_player=False,
            llm_config={
                "system_instruction_extras": "你说话简短、带判断感，很容易把'懂事''大局'挂在嘴边。你会偏心，也会在公开场合用一句话把人按回去，但会把偏心包装成理性。"
            },
        ),
        CharacterConfig(
            name="沈夫人",
            agent_runtime="hermes",
            role="母亲",
            personality="讲究分寸、重礼数、情绪藏得很深。她对林见微有亏欠，却更本能地维护自己亲手养大的沈昭宁。",
            goals=[
                "维持沈家的体面和秩序",
                "避免自己显得残忍，但也不愿让沈昭宁太难堪",
                "用委婉方式要求林见微理解大家的难处",
                "在冲突里优先安抚沈昭宁，而不是先听林见微解释",
            ],
            initial_beliefs=[
                {"statement": "保护沈昭宁的情绪也是弥补家庭错误的一部分", "confidence": 0.85, "source": "多年养育关系"},
            ],
            initial_secrets=["她对亲生女儿有愧疚，但暂时不愿承认自己的偏心"],
            initial_needs=[
                NeedConfig(name="家庭体面", pressure=0.6, drift_per_turn=0.025, description="冲突越公开，她越想用礼数和委婉要求恢复表面平静"),
            ],
            initial_traits=[
                TraitConfig(trait_id="decorous", intensity=0.85),
                TraitConfig(trait_id="risk_averse", intensity=0.8),
            ],
            risk_tolerance=0.25,
            is_player=False,
            llm_config={
                "system_instruction_extras": "你不会轻易摊牌。你擅长用礼貌、停顿、旧事和'你要懂事'来给人压力，也会拿分寸和家教做比较。除非证据非常明确，否则不要直接责骂沈昭宁。"
            },
        ),
        CharacterConfig(
            name="沈砚川",
            agent_runtime="hermes",
            role="哥哥",
            personality="冷静、护短、不喜欢失控。他默认沈昭宁是自己妹妹很多年，因此会下意识站在她那边。",
            goals=[
                "让今晚顺利过去",
                "在任何误会里先帮沈昭宁收场",
                "观察林见微是否会给这个家添乱",
                "一旦场面失控，优先要求林见微退一步",
            ],
            initial_beliefs=[
                {"statement": "沈昭宁遇到冲突时通常需要自己先替她收场", "confidence": 0.9, "source": "多年兄妹相处"},
            ],
            initial_needs=[
                NeedConfig(name="局面控制", pressure=0.62, drift_per_turn=0.04, description="他无法容忍家宴失控，压力会推动他打断和收场"),
            ],
            initial_traits=[
                TraitConfig(trait_id="protective", intensity=0.85),
                TraitConfig(trait_id="controlled", intensity=0.75),
            ],
            risk_tolerance=0.55,
            is_player=False,
            llm_config={
                "system_instruction_extras": "你说话利落、克制、带一点居高临下。你会打断、定调、收场，并把玩家放回'别添乱'的位置上。你的偏心是自然流露，不是故意恶毒。"
            },
        ),
        CharacterConfig(
            name="陆承泽",
            agent_runtime="hermes",
            role="沈昭宁的未婚夫",
            personality="沉稳、审慎、看重旧情与熟悉感。他不一定故意为难林见微，但在关键时刻多半会先替沈昭宁解释。",
            goals=[
                "维持饭局体面",
                "保护沈昭宁，不让她在众人面前难堪",
                "把林见微的锋芒和不适都理解成不稳定因素",
                "在需要站队时，自然而然站到沈昭宁一边",
            ],
            initial_beliefs=[
                {"statement": "维护沈昭宁就是维护现有关系与场面稳定", "confidence": 0.8, "source": "旧有婚约关系"},
            ],
            initial_needs=[
                NeedConfig(name="关系稳定", pressure=0.56, drift_per_turn=0.03, description="婚约与旧情受到挑战时，他会更主动维护熟悉关系"),
            ],
            initial_traits=[
                TraitConfig(trait_id="loyal", intensity=0.8),
                TraitConfig(trait_id="cautious", intensity=0.7),
            ],
            risk_tolerance=0.35,
            is_player=False,
            llm_config={
                "system_instruction_extras": "你说话冷静、克制、貌似公平，但立场常常不自觉偏向沈昭宁。你会替她挡话、先替她解释、用讲道理的口吻压掉玩家的时机，不要把自己写成明显反派。"
            },
        ),
        CharacterConfig(
            name="周姨",
            agent_runtime="hermes",
            role="管家/家中老人",
            personality="谨慎、心软、嘴严。她知道旧事比别人多一点，也更容易对林见微生出怜惜，但不敢明着站队。",
            goals=[
                "维持家中日常运转",
                "尽量避免把旧事闹到台面上",
                "在不丢饭碗的前提下，偶尔给林见微一点隐秘提醒",
            ],
            initial_beliefs=[
                {"statement": "林见微对沈家的旧事几乎一无所知", "confidence": 0.9, "source": "家中旧事"},
            ],
            initial_secrets=["她记得当年接回孩子时的一些日期和说法彼此对不上"],
            initial_needs=[
                NeedConfig(name="生计安全", pressure=0.45, drift_per_turn=0.02, description="旧事越逼近台面，她越需要在良心与饭碗之间权衡"),
            ],
            initial_traits=[
                TraitConfig(trait_id="cautious", intensity=0.9),
                TraitConfig(trait_id="compassionate", intensity=0.55),
            ],
            risk_tolerance=0.15,
            initial_obligations=[
                ObligationConfig(
                    obligation_id="return_old_ledger",
                    title="饭后把旧账册送回书房",
                    summary="不要让旧账册继续留在佣人可能翻到的地方",
                    due_step=5,
                    grace_steps=1,
                    wake_before_steps=1,
                    pressure_need="生计安全",
                    completion_conditions=[
                        StateCondition(
                            scope="world_object",
                            target="旧账册",
                            path="location",
                            operator="eq",
                            value="书房",
                        )
                    ],
                )
            ],
            activation_policy="background",
            background_interval=2,
            is_player=False,
            llm_config={
                "system_instruction_extras": "你说话朴素、谨慎，容易在某些旧物和旧称呼上停顿，但会很快改口。不要故意把自己写得鬼鬼祟祟。"
            },
        ),
    ],
)
